# Generated by Django 5.2.9 on 2026-01-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autopartsApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="products",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
