# Generated by Django 5.2.9 on 2026-01-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autopartsApp", "0002_category_updated_at_products_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Formatos permitidos: JPG, PNG",
                null=True,
                upload_to="category_images/",
                verbose_name="Imagen de Categoría",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Formatos permitidos: JPG, PNG",
                null=True,
                upload_to="product_images/",
                verbose_name="Imagen de Producto",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Formatos permitidos: JPG, PNG",
                null=True,
                upload_to="subcategory_images/",
                verbose_name="Imagen de Subcategoría",
            ),
        ),
    ]
