# Generated by Django 5.2.9 on 2026-02-07 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("autopartsApp", "0003_category_image_products_image_subcategory_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del Banner"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Formatos permitidos: JPG, PNG",
                        upload_to="banners/",
                        verbose_name="Imagen del Banner",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("inicio", "Inicio"),
                            ("categorias", "Categorías"),
                            ("subcategorias", "Subcategorías"),
                            ("productos", "Productos"),
                        ],
                        help_text="Dónde se mostrará el banner",
                        max_length=20,
                        verbose_name="Sección",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de finalización")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "order",
                    models.IntegerField(
                        default=0, verbose_name="Orden de visualización"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo si el banner es para una categoría en particular",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autopartsApp.category",
                        verbose_name="Categoría específica",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banners_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo si el banner es para una subcategoría en particular",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autopartsApp.subcategory",
                        verbose_name="Subcategoría específica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
