# Generated by Django 5.2.9 on 2026-01-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accountsApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Formatos permitidos: JPG, PNG",
                null=True,
                upload_to="profile_images/",
                verbose_name="Foto de Perfil",
            ),
        ),
    ]
